version: "3.8"

services:
  pvawnings:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - pvawnings_code:/app
      - /app/node_modules
    command: sh -c "NEXT_PUBLIC_BACKEND_API_URL=${NEXT_PUBLIC_BACKEND_API_URL} npm run build && npm start -- -p 80"

volumes:
  pvawnings_code: